data:
  lang: 'cmu'
  text_cleaners: ['transliteration_cleaners']
  speakers: ['ERR-uudised-Tonu_Karjatse', 'UT-uudised-Mari', 'ERR-uudised-Tarmo_Maiberg', 'EKI-yksiklaused-Liivika', 'ERR-uudised-Vallo_Kelmsaar', 'ERR-uudised-Kai_Vare', 'UT-uudised-Kalev', 'EKI-yksiklaused-Kylli', 'EKI-ilukirjandus-Kylli', 'EKI-yksiklaused-Kersti', 'ERR-uudised-Birgit_Itse', 'EKI-ilukirjandus-Meelis', 'ERR-uudised-Indrek_Kiisler', 'UT-uudised-Albert', 'ERR-uudised-Meelis_Kompus', 'EKI-yksiklaused-Meelis', 'UT-uudised-Vesta'] # list of speaker ids (last elements of each metadata line)
  train_dir: '/gpfs/space/home/zuppur/cotatron/data/preprocessed_v2/'     # root path of data. The first elements of each metadata lines should be a relative path with respect to this.
  train_meta: '/gpfs/space/home/zuppur/cotatron/datasets/metadata/estonian_metadata.txt' # path of training data's metadata
  val_dir: '/gpfs/space/home/zuppur/cotatron/data/preprocessed_v2/'       # same as train_dir.
  val_meta: '/gpfs/space/home/zuppur/cotatron/datasets/metadata/estonian_metadata.txt' # path of validation data's metadata
  cmudict_path: '/gpfs/space/home/zuppur/cotatron/datasets/cmudict-0.7b_fix.txt'  # path of cmudict-0.7b_fix.txt
###########################
audio: # WARNING! This cannot be changed unlees you're planning to train the MelGAN vocoder by yourself.
  n_mel_channels: 80
  filter_length: 1024
  hop_length: 256
  win_length: 1024
  sampling_rate: 22050
  mel_fmin: 70.0
  mel_fmax: 8000.0
###########################
chn:
  # text encoder
  encoder: 512
  # speaker encoder
  speaker:
    cnn: [32, 32, 64, 64, 128, 128]
    token: 256
  # residual encoder
  residual: [32, 32, 64, 64, 128, 128]
  residual_out: 1
  # TTS decoder
  prenet: 256
  postnet: 512
  attention_rnn: 512
  attention: 128
  decoder_rnn: 512
  static: 8
  dynamic: 8
###########################
ker:
  encoder: 5
  ### DCA ###
  static: 21
  dynamic: 21
  causal: 11
  alpha: 0.1
  beta: 0.9
  ###########
  postnet: 5
###########################
depth:
  encoder: 3
  prenet: 2
  postnet: 5
