data:
  lang: 'cmu'
  text_cleaners: ['english_cleaners']
  speakers: ['6147', '7178', '5652', '7190', '4640', '6181', '40', '1578', '2092', '1069', '5678', '8238', '7226', '1088', '6209', '4160', '8770', '5703', '4680', '587', '78', '3664', '83', '87', '2136', '1116', '4195', '7278', '7794', '118', '5750', '7800', '8312', '125', '6272', '8324', '2182', '8838', '7302', '2196', '669', '6818', '3240', '3242', '4267', '5808', '4788', '6836', '696', '3259', '6848', '196', '7367', '200', '4297', '5322', '730', '5339', '1246', '6367', '8419', '7402', '1263', '2289', '6385', '250', '254', '4362', '6415', '5393', '3857', '8468', '2836', '7447', '2843', '6437', '3879', '4397', '1841', '6454', '4406', '831', '1867', '6476', '7505', '7511', '2911', '3436', '2416', '8051', '374', '887', '6529', '6019', '2436', '2952', '3982', '3983', '7059', '405', '8088', '7067', '3486', '5022', '8609', '8098', '7078', '1963', '8108', '6064', '1970', '4018', '8629', '8123', '6078', '446', '6081', '3526', '460', '4051', '1502', '5104', '4088'] # list of speaker ids (last elements of each metadata line)
  train_dir: '/gpfs/hpc/home/zuppur/cotatron/data/'     # root path of data. The first elements of each metadata lines should be a relative path with respect to this.
  train_meta: '/gpfs/hpc/home/zuppur/cotatron/datasets/metadata/libritts_train_clean_100_audiopath_text_sid_shorterthan10s_atleast5min_train_filelist_22k.txt' # path of training data's metadata
  val_dir: '/gpfs/hpc/home/zuppur/cotatron/data/'       # same as train_dir.
  val_meta: '/gpfs/hpc/home/zuppur/cotatron/datasets/metadata/libritts_train_clean_100_audiopath_text_sid_atleast5min_val_filelist_22k.txt' # path of validation data's metadata
  cmudict_path: '/gpfs/hpc/home/zuppur/datasets/cmudict-0.7b_fix.txt'  # path of cmudict-0.7b_fix.txt
###########################
audio: # WARNING! This cannot be changed unlees you're planning to train the MelGAN vocoder by yourself.
  n_mel_channels: 80
  filter_length: 1024
  hop_length: 256
  win_length: 1024
  sampling_rate: 22050
  mel_fmin: 70.0
  mel_fmax: 8000.0
###########################
chn:
  # text encoder
  encoder: 512
  # speaker encoder
  speaker:
    cnn: [32, 32, 64, 64, 128, 128]
    token: 256
  # residual encoder
  residual: [32, 32, 64, 64, 128, 128]
  residual_out: 1
  # TTS decoder
  prenet: 256
  postnet: 512
  attention_rnn: 512
  attention: 128
  decoder_rnn: 512
  static: 8
  dynamic: 8
###########################
ker:
  encoder: 5
  ### DCA ###
  static: 21
  dynamic: 21
  causal: 11
  alpha: 0.1
  beta: 0.9
  ###########
  postnet: 5
###########################
depth:
  encoder: 3
  prenet: 2
  postnet: 5
